
<cf_screentop height="100%" jquery="Yes" systemmodule="Accounting"
			  functionclass="Window"
			  functionname="Transaction Edit" 
			  html="yes" layout="webapp" line="no" banner="green" label="Edit Transaction" scroll="yes">

<!--- create temp tables --->

<CF_DropTable dbName="AppsQuery" tblName="#SESSION.acc#GledgerHeader_#client.sessionNo#"> 
<CF_DropTable dbName="AppsQuery" tblName="#SESSION.acc#GledgerLine_#client.sessionNo#"> 

<!--- populate header table --->

<cfquery name="GledgerHeader"
datasource="AppsLedger" 
username="#SESSION.login#" 
password="#SESSION.dbpw#">
    SELECT TOP 1 J.*, 
	       T.GLAccount as ContraGLAccount, 
		   T.ReferenceName as ContraGLAccountDescription, 
		   'Credit' as ContraGLAccountType,
		   AmountDebit,
		   T.ParentJournal,
		   T.ParentJournalSerialNo,
		   T.ParentTransactionId,
		   T.ParentLineId
	INTO   UserQuery.dbo.#SESSION.acc#GledgerHeader_#client.sessionNo#
	FROM   TransactionHeader J LEFT OUTER JOIN 
	       TransactionLine T ON J.Journal = T.Journal AND  J.JournalSerialNo = T.JournalSerialNo AND T.TransactionSerialNo = '0'
	WHERE  J.Journal = '#URL.Journal#'
	AND    J.JournalSerialNo = '#URL.JournalSerialNo#'		
	ORDER BY T.ParentJournal 	
</cfquery>

<!--- determine if the transaction has a default contra-account --->

<cfquery name="getContra"
datasource="AppsQuery" 
username="#SESSION.login#" 
password="#SESSION.dbpw#">
	SELECT * FROM #SESSION.acc#GledgerHeader_#client.sessionNo#	
</cfquery>

<cfif getContra.ContraGLAccount eq "">
	
	<cfquery name="ContraAccount"
		datasource="AppsLedger" 
		username="#SESSION.login#" 
		password="#SESSION.dbpw#">
		    SELECT   *
			FROM     JournalAccount A 
			WHERE    Journal = '#url.Journal#' 	
			AND      Mode = 'Contra'
	</cfquery>
	
	<cfif ContraAccount.recordcount eq "1">
		
		<cfquery name="HeaderUpdate"
		datasource="AppsQuery" 
		username="#SESSION.login#" 
		password="#SESSION.dbpw#">
			UPDATE #SESSION.acc#GledgerHeader_#client.sessionNo#
			SET    ContraGLAccount = '#ContraAccount.GLAccount#'	
		</cfquery>
	
	</cfif>

</cfif>

<cfquery name="HeaderUpdate"
datasource="AppsQuery" 
username="#SESSION.login#" 
password="#SESSION.dbpw#">
	UPDATE #SESSION.acc#GledgerHeader_#client.sessionNo#
	SET    ContraGLAccountType = 'Debit'
	WHERE  AmountDebit <> 0.0
</cfquery>

<!--- populate lines table --->

<cfquery name="GledgerLine"
datasource="AppsLedger" 
username="#SESSION.login#" 
password="#SESSION.dbpw#">
 	SELECT IDENTITY(INT,1,1) as Serialno,T.*
 	INTO   UserQuery.dbo.#SESSION.acc#GledgerLine_#client.sessionNo#
	FROM   TransactionLine T, TransactionHeader J
	WHERE  T.Journal       = '#URL.Journal#'
	AND    T.JournalSerialNo = '#URL.JournalSerialNo#'
	AND    T.Journal = J.Journal
	AND    T.JournalSerialNo = J.JournalSerialNo
	ORDER BY T.TransactionSerialNo ASC, T.Created ASC
</cfquery>

<cfquery name="HeaderSelect"
datasource="AppsLedger" 
username="#SESSION.login#" 
password="#SESSION.dbpw#">
    SELECT * 
	FROM   TransactionHeader
	WHERE  Journal = '#URL.Journal#'
	AND    JournalSerialNo = '#URL.JournalSerialNo#'
</cfquery>

<cfquery name="getSource"
datasource="AppsLedger" 
username="#SESSION.login#" 
password="#SESSION.dbpw#">
    SELECT * 
	FROM   Ref_TransactionSource
	WHERE  Code = '#HeaderSelect.TransactionSource#'
</cfquery>

<cfif getSource.editmode eq "1">

	   <cfset editmode = "full">
	   
<cfelse>	   

	<!--- transaction lines generated by source should not be always editable here but are modified by the source --->

	<cfset editmode = "limited">
	
</cfif>	

<cfset url.mission       = HeaderSelect.Mission>
<cfset url.OrgUnitOwner  = HeaderSelect.OrgUnitOwner>
<cfset url.Journal       = HeaderSelect.Journal>
<cfset url.AccountPeriod = HeaderSelect.AccountPeriod>

<table width="100%" height="100%">
	<tr><td width="100%" height="100%" valign="top">
		<cf_divscroll style="height:100%; min-height:100%">
			<cfinclude template="Transaction.cfm">
		</cf_divscroll>
	</td></tr>
</table>
