
<cf_screentop height="100%" scroll="yes" html="No">

<cfparam name="FORM.Select" default="">

<cfif ParameterExists(Form.Return)> 

     <cfif FORM.Select eq "">
      <cf_message message = "You have not identified any candidates. Operation aborted."
       return = "back">
       <cfabort>
     </cfif>

     <cf_wait text="Please wait . .">

     <cfquery name="SelectRoster" 
     datasource="AppsSelection" 
     username="#SESSION.login#" 
     password="#SESSION.dbpw#">
	     SELECT  S.PersonNo, S.ApplicantNo, F.FunctionId
	     FROM    ApplicantSubmission S INNER JOIN
	             Applicant A ON S.PersonNo = A.PersonNo INNER JOIN
	             ApplicantFunction F ON S.ApplicantNo = F.ApplicantNo
	     WHERE   F.FunctionId = '#url.docno#'
		 AND     S.PersonNo IN (#PreserveSingleQuotes(FORM.Select)#)
		 <cfif   Form.Status eq "1">
		 AND     F.Status != '2'
		 </cfif>
	 </cfquery>
	 
	 <cfif SelectRoster.recordcount gt "0">
	 
	     <cfset can = "#SelectRoster.recordcount# candidates">
	 
	     <cfif form.Status eq "9">
	 
		   <cf_RosterActionNo ActionCode="FUN" 
		       ActionRemarks="Roster denial #can#"> <!---old "Batch denial"--->
		 
		 <cfelse>
		 
		   <cf_RosterActionNo ActionCode="FUN" 
		      ActionRemarks="Roster clearance #can#"> <!---old "Batch clearance"--->
		 
		 </cfif>
		 
		 <!--- loop accross all entries here --->
		 
		 <cftransaction action="BEGIN">
	
	     <cfloop query = "SelectRoster">
	
			<!--- roster action line --->
			
			<cfquery name="UpdateFunctionStatusAction" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			INSERT INTO  ApplicantFunctionAction
			   (ApplicantNo,
			   FunctionId, 
			   RosterActionNo, 
			   Status)
			VALUES 
			   ('#ApplicantNo#',
			   '#url.docno#',
			   #RosterActionNo#,
			   '#form.Status#')
			</cfquery> 
			
			<cfquery name="Verify" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			SELECT    PersonNo
			FROM      ApplicantReview
			WHERE     PersonNo = '#PersonNo#' 
			AND       ReviewCode = 'MED'
			</cfquery>   
			
			<CFIF Verify.recordCount eq 0>   
			
				<cfquery name="InsertClearance" 
				datasource="AppsSelection" 
				username="#SESSION.login#" 
				password="#SESSION.dbpw#">
				INSERT INTO ApplicantReview (PersonNo, 
				                                ReviewCode, 
												Status, 
												ReviewRemarks, 
												OfficerUserId, 
												OfficerLastName, 
												OfficerFirstName, 
												Created)
				VALUES  ('#PersonNo#', 
				         'MED', 
						 '0', 
						 'Generated by clearance', 
						 '#SESSION.acc#', 
						 '#SESSION.last#', 
						 '#SESSION.first#', 
						 getDate())
				</cfquery>
				 
			</CFIF>
			
			<!--- now update the status --->
			
			<cfquery name="UpdateFunctionStatus" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			UPDATE    ApplicantFunction 
			SET       Status                = '#Form.Status#',
		 			  StatusDate            = getDate(), 
			          RosterGroupMemo       = '#Form.Memo#'
			WHERE     ApplicantNo           = '#SelectRoster.ApplicantNo#'
			  AND     FunctionId            = '#url.docno#'     
			</cfquery>
			
			<!--- now remove candidates --->
			
			<cfquery name="Empty" 
	        datasource="AppsSelection" 
	        username="#SESSION.login#" 
	        password="#SESSION.dbpw#">
		    DELETE FROM RosterSearchResult
		    WHERE  SearchId = '#URL.ID1#'
			AND    PersonNo IN (#PreserveSingleQuotes(FORM.Select)#)
		    </cfquery>
						
	     </cfloop>
			
	     </cftransaction>
	 
	 </cfif>
	 
	 <cf_waitEnd>
	 	
     <script language="JavaScript">

	    <cfoutput>
   	        window.location = "ResultListing.cfm?mode=#url.mode#&docno=#url.docno#&ID=#URL.ID#&ID1=#URL.ID1#&ID2=#URL.ID2#&ID3=#URL.ID3#&Page=#Form.Page#&Lay=#Form.Lay#"
		</cfoutput>
				
     </script>
	
 
<!--- --------- ---->
<!--- EXPORTING ---->
<!--- --------- ---->

<cfelseif ParameterExists(Form.ExportExcel)> 

     <cfif FORM.Select eq "">
      <cf_message message = "You have not identified any candidates. Operation aborted." return = "back">
       <cfabort>
     </cfif>

	 
	 <!---
	<cftry>
	--->
	
		<cf_wait1 icon="clock">
		
		<CF_DropTable dbName="AppsQuery" tblName="#SESSION.acc#RosterTmp">
		
		<cfquery name="Staffing" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
		    SELECT Max(AssignmentNo) as AssignmentNo
			INTO   userQuery.dbo.#SESSION.acc#RosterTmp
			FROM   Employee.dbo.vwAssignment
			WHERE  IndexNo IN (SELECT IndexNo 
			                   FROM Applicant A 
							   WHERE A.PersonNo IN (#PreserveSingleQuotes(FORM.Select)#))
			AND    DateEffective <= getDate()
			AND    DateExpiration >= getDate()
			AND    AssignmentStatus IN ('0','1') 	
					  
		</cfquery>	

	 		
		<cfloop index="itm" from="1" to="2">	
					 
			<CF_DropTable dbName="AppsQuery" tblName="#SESSION.acc#Roster#itm#">
									 	 
			<cfquery name="Result1" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			SELECT A.IndexNo, 
			       A.LastName, 
				   A.LastName2,
				   A.FirstName, 
				   A.MiddleName, 
				   A.Gender, 
				   A.DOB as BirthDate, 
				   A.BirthNationality,
				   A.Nationality,
				   A.PersonNo,
			      (SELECT TOP 1 TelephoneNo 
				    FROM  ApplicantAddress 
					WHERE PersonNo = A.PersonNo) as TelephoneNo, 
				   A.EMailAddress,		
				   (SELECT TOP 1 ContractLevel 
				    FROM   Employee.dbo.skPersonContract C 
					WHERE  A.IndexNo = C.IndexNo 
					AND    ActionStatus = '1' 
					ORDER BY DateEffective DESC) as ContractLevel
			INTO  userQuery.dbo.#SESSION.acc#Roster#itm#
			FROM  Applicant A 
			WHERE  
			<cfif itm eq "1">  
				A.PersonNo IN (SELECT PersonNo 
			                   FROM RosterSearchResult 
				               WHERE  SearchId = '#URL.ID1#'
							   AND  Status = '1'
							   AND  PersonNo = A.PersonNo
							   AND  PersonNo IN (#PreserveSingleQuotes(FORM.Select)#)
							   )
			<cfelse>
				A.PersonNo IN (SELECT PersonNo 
			                   FROM   RosterSearchResult 
				               WHERE  SearchId = '#URL.ID1#'
							   AND    PersonNo = A.PersonNo
							   AND  PersonNo IN (#PreserveSingleQuotes(FORM.SelectedAll)#)) 
			</cfif>
			ORDER BY A.LastName,A.FirstName
			</cfquery>			
		
		</cfloop>

		
		<CF_DropTable dbName="AppsQuery" tblName="#SESSION.acc#RosterTmp">
				
		<cf_waitEnd>
		
		<!---
		
		<cfcatch>
		
		 <cf_message message = "Export was not generated. Please try again."
	       return = "back">
    	   <cfabort>
		
		</cfcatch>
		
	</cftry>	
	
	--->
				 
	 <cfquery name="Layout" 
		datasource="AppsSystem" 
		username="#SESSION.login#" 
		password="#SESSION.dbpw#">
	    SELECT    ControlId
		FROM      Ref_ReportControl R
	    WHERE     FunctionName = 'RosterSearchExport'
		AND       TemplateSQL  = 'Application'
	</cfquery>
	
	<cfif Layout.recordcount eq "0">
	
		<cf_assignid>
		
		<cfquery name="Insert" 
			datasource="AppsSystem" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			INSERT INTO Ref_ReportControl
					(ControlId,
					 SystemModule, 
					 FunctionClass, 
					 FunctionName, 
					 ReportRoot,					 
					 TemplateSQL, 
					 OfficerUserId, 
					 OfficerLastName, 
					 OfficerFirstName)
			 VALUES ('#rowGuid#',
			         'Roster',
			         'Reports',
					 'RosterSearchExport',					 
					 'Application',
					 'Application',
			         '#SESSION.acc#',
					 '#SESSION.last#',
					 '#SESSION.first#')
			</cfquery>	
			
			<cfquery name="Insert" 
			datasource="AppsSystem" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
				INSERT INTO Ref_ReportControlOutput
						(ControlId, 					 
						 DataSource, 
						 OutputClass,
						 VariableName, 
						 OutputName, 
						 OfficerUserId, 
						 OfficerLastName, 
						 OfficerFirstName) 
				 VALUES ('#rowguid#',					 
					     'appsQuery',
					     'variable',
					     'table1', 
					     'Selected candidates only',
					     '#SESSION.acc#',
					     '#SESSION.last#',
					     '#SESSION.first#')
			</cfquery>
			
			<cfquery name="Insert" 
			datasource="AppsSystem" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
				INSERT INTO Ref_ReportControlOutput
						(ControlId, 					 
						 DataSource, 
						 OutputClass,
						 VariableName, 
						 OutputName, 
						 OfficerUserId, 
						 OfficerLastName, 
						 OfficerFirstName) 
				 VALUES ('#rowguid#',					 
					    'appsQuery',
					    'variable',
					    'table2', 
					    'All candidates',
					    '#SESSION.acc#',
					    '#SESSION.last#',
					    '#SESSION.first#')
			</cfquery>
	
	</cfif>
	
	 <cfquery name="Layout" 
		datasource="AppsSystem" 
		username="#SESSION.login#" 
		password="#SESSION.dbpw#">
	    SELECT    ControlId
		FROM      Ref_ReportControl R
	    WHERE     FunctionName = 'RosterSearchExport'
		AND       TemplateSQL  = 'Application'
	</cfquery>
	
			
	<cfset context       = "application">	
	<cfset URL.ControlId = Layout.ControlId>
		
	<cfoutput>
		<script language="JavaScript">		
	  	  window.location = "#SESSION.root#/Tools/CFReport/ExcelFormat/FormatExcel.cfm?mode=embed&table1=#SESSION.acc#Roster1&table2=#SESSION.acc#Roster2&controlid=#Layout.ControlId#"		 		 
		</script>
	</cfoutput>
	

<cfelseif ParameterExists(Form.PDF)> 
	
	<cfquery name="Identify" 
	     datasource="AppsSelection" 
	     username="#SESSION.login#" 
	     password="#SESSION.dbpw#">
		 UPDATE RosterSearchResult
		 Set Status = '0'
		 WHERE  SearchId = '#URL.ID1#'
		</cfquery>	
	
	<cfquery name="Identify" 
	     datasource="AppsSelection" 
	     username="#SESSION.login#" 
	     password="#SESSION.dbpw#">
		 UPDATE RosterSearchResult
		 Set Status = '1'
		 WHERE  SearchId = '#URL.ID1#'
		 AND PersonNo IN (#PreserveSingleQuotes(FORM.Select)#)
		</cfquery>	
		
	<cfquery name="Stage" 
	     datasource="AppsSelection" 
	     username="#SESSION.login#" 
	     password="#SESSION.dbpw#">
		 UPDATE RosterSearch
		 SET Status = '11'
		 WHERE  SearchId = '#URL.ID1#'
		</cfquery>	
		
	<script language="javascript">
		   <cfoutput>
		      window.open("../../Candidate/php_sum.cfm?sr=#URL.ID1#","_blank", "width=850, height=710, toolbar=no, scrollbars=yes, resizable=yes")
		   </cfoutput>
	</script>	
		
	<script language="javascript">
	      history.back()
	</script>	
	
</cfif> 


