
<cf_AssignId>

<cfparam name="Form.ActionRemarks" default="">
<cfparam name="Form.Remarks" default="">
<cfparam name="Form.Status" default="0">

<cfset setStatus = form.Status>

<cfif Len(Form.ActionRemarks) gt 300>      
       <cf_alert message = "You entered a memo that exceeded the allowed size of 300 characters."> 
       <cfabort> 
</cfif>

<cfif Len(Form.Remarks) gt 300>	   
	   <cf_alert message = "You entered a memo that exceeded the allowed size of 300 characters.">
	   <cfabort>
</cfif>

<cfif url.process eq "memo"> 

	<cfquery name="UpdateFunctionStatus" 
		datasource="AppsSelection" 
		username="#SESSION.login#" 
		password="#SESSION.dbpw#">
		UPDATE    ApplicantFunction 
		SET       RosterGroupMemo       = '#Form.Remarks#' 
		WHERE     ApplicantNo           = '#Form.ApplicantNo#'
		AND       FunctionId            = '#Form.FunctionId#'     
	 </cfquery>
		
<cfelseif url.process eq "close" or url.process eq "open"> 

	<cfif ParameterExists(Form.Status)> 
		
		<!--- Roster --->
		<cfquery name="Param" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			SELECT    *
			FROM      Ref_StatusCode
			WHERE     Owner  = '#URL.Owner#' 
			AND       Id     = 'FUN' 
			AND       Status = '#Form.Status#'
		</cfquery>
			
		<cfparam name="Form.DecisionCode" default="">
	
		<cfif Param.EnforceReason eq "1" and Form.DecisionCode eq "">	
			
			 <cf_alert message = "You must select one or more reasons for your decision."
			  return = "back">
			  
			 <cfabort>
	
		</cfif>
		
		<cfif Param.EnforceRemarks eq "1" and Form.ActionRemarks eq "">
		
			 <cf_alert message = "You must enter remarks for your decision."
			  return = "back">
			  
			 <cfabort>
		
		</cfif>
	
	</cfif>
			
	<cftransaction action="BEGIN">
		
		<!--- Roster action logging --->
		
		<cf_RosterActionNo ActionRemarks="#FORM.ActionRemarks#" ActionCode="FUN">  
		
		<cfset actionNo = RosterActionNo>
			
		<!--- create medical clearance record --->
		
		<cfquery name="Submission" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			SELECT    *
			FROM      ApplicantSubmission
			WHERE     ApplicantNo = '#Form.ApplicantNo#'
		</cfquery>
		
		<cfquery name="Verify" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			SELECT    *
			FROM      ApplicantReview
			WHERE     PersonNo = '#Submission.PersonNo#' 
			AND       ReviewCode = 'MED'
			</cfquery>
			
			<CFIF Verify.recordCount eq 0> 
			
				<cfquery name="InsertClearance" 
				datasource="AppsSelection" 
				username="#SESSION.login#" 
				password="#SESSION.dbpw#">
					INSERT INTO ApplicantReview 
					        (PersonNo, 
					         ReviewCode, 
							 Status, 
							 ReviewRemarks, 
							 OfficerUserId, 
							 OfficerLastName, 
							 OfficerFirstName, 
							 Created)
					VALUES  ('#Submission.PersonNo#', 
					         'MED', 
							 '0', 
							 'Generated by clearance', 
							 '#SESSION.acc#', 
							 '#SESSION.last#', 
							 '#SESSION.first#', 
							 getDate())
				</cfquery>
				
			</CFIF>
		
		<!--- competence upload --->
				
		<cfquery name="Clear" 
		datasource="AppsSelection" 
		username="#SESSION.login#" 
		password="#SESSION.dbpw#">	
			DELETE FROM ApplicantCompetence
			WHERE  ApplicantNo = '#Form.ApplicantNo#' 
		</cfquery>
		
		<!--- add background fields level, geo, exp after identifying the assigned serialNo --->
		
		<cfparam name="Form.FieldId" default="">
				 
		<cfloop index="Item" 
		        list="#Form.FieldId#" 
		        delimiters="' ,">
				
				<cfquery name="InsertCompetence" 
				datasource="AppsSelection" 
				username="#SESSION.login#" 
				password="#SESSION.dbpw#">
				INSERT INTO dbo.ApplicantCompetence 
				         (ApplicantNo,
						 CompetenceId,
						 Status,
						 OfficerUserId,
						 OfficerLastName,
						 OfficerFirstName)
				  VALUES ('#Form.ApplicantNo#', 
				          '#Item#',
						  '0',
						  '#SESSION.acc#',
						  '#SESSION.last#',
						  '#SESSION.first#')</cfquery>
				  
		</cfloop>	
				
		<!--- check if master record exists --->
		
		<cfquery name="Verify"
		datasource="AppsSelection"
		username="#SESSION.login#"
		password="#SESSION.dbpw#">
			SELECT  ExperienceId
			FROM    ApplicantBackground
			WHERE   ExperienceCategory = 'Miscellaneous' 
			   AND  ApplicantNo = '#FORM.ApplicantNo#'
		</cfquery>
		
		<cfif Verify.recordCount gt 0>
		
		   <cfset expid = Verify.ExperienceId>
		
		<cfelse>
		
			<cfquery name="InsertBackground" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
				INSERT INTO ApplicantBackground 
				         (ApplicantNo,
						 ExperienceCategory,
						 Remarks,
						 Status,
						 OfficerUserId,
						 OfficerLastName,
						 OfficerFirstName)
				  VALUES ('#FORM.ApplicantNo#', 
				       	  'Miscellaneous',
						  'Assessment on background',
						  '0',
						  '#SESSION.acc#',
						  '#SESSION.last#',
						  '#SESSION.first#')
			</cfquery>
					  
			<cfquery name="Verify" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
				SELECT   ExperienceId 
				FROM     ApplicantBackground R
				WHERE    R.ExperienceCategory = 'Miscellaneous' 
				AND      ApplicantNo = '#FORM.ApplicantNo#'
			</cfquery>
			
			<cfset expid = Verify.ExperienceId>		  
		
		</cfif>
		
		<!--- now add other applications that are forwarded --->
				
		   <cfparam name="Form.FunctionId" default="">
		   <cfparam name="Form.FunctionIdSelect" default=""> 
					
			<cfquery name="Edition" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
				SELECT * 
				FROM   Ref_ParameterOwner P,
				       Ref_SubmissionEdition S 
				WHERE  P.Owner = '#URL.Owner#'
				AND    S.SubmissionEdition = P.DefaultRoster
			</cfquery>
			  
			<cfloop index="id" 
			        list="#Form.FunctionIdSelect#" 
			        delimiters=",">
					
				<cfquery name="Check" 
				datasource="AppsSelection" 
				username="#SESSION.login#" 
				password="#SESSION.dbpw#">
				SELECT * 
				FROM   ApplicantFunction 
				WHERE  ApplicantNo = '#FORM.ApplicantNo#'
				AND    FunctionId =  '#id#'
				</cfquery>
				
				<cfif check.recordcount eq "0">
			        				
					<cfquery name="InsertFunction" 
					datasource="AppsSelection" 
					username="#SESSION.login#" 
					password="#SESSION.dbpw#">
					
					INSERT INTO dbo.ApplicantFunction 
				         (ApplicantNo,
						 FunctionId,
						 Status,
						 StatusDate,
						 FunctionJustification, 
						 RosterGroupMemo,
						 OfficerUserId,
						 OfficerLastName,
						 OfficerFirstName)
					VALUES ('#FORM.ApplicantNo#', 
				      	  '#id#',
						  '#Edition.DefaultStatus#',
						  getdate(),
						  '#Form.Remarks#', 
						  '#Form.ActionRemarks#',
						  '#SESSION.acc#',
						  '#SESSION.last#',
						  '#SESSION.first#')
				    </cfquery>
						  
					<cfquery name="UpdateFunctionStatusAction" 
					datasource="AppsSelection" 
					username="#SESSION.login#" 
					password="#SESSION.dbpw#">
					INSERT INTO  ApplicantFunctionAction
						   (ApplicantNo,
						   FunctionId, 
						   RosterActionNo, 
						   FunctionJustification, 
						   Status)
					VALUES 
						   ('#Form.ApplicantNo#',
						   '#id#',
						   #ActionNo#,
						   '#Form.Remarks#', 
						   '0')
					</cfquery> 	  			
				
					<cfif Edition.DefaultStatus neq "0">
					
					   <cf_RosterActionNo ActionRemarks="Proposed" ActionCode="FUN">  
					
					   <cftry>
					   
						<cfquery name="UpdateFunctionStatusAction" 
						datasource="AppsSelection" 
						username="#SESSION.login#" 
						password="#SESSION.dbpw#">
						INSERT INTO  ApplicantFunctionAction
							   (ApplicantNo,
							   FunctionId, 
							   RosterActionNo, 
							   Status)
						VALUES 
							   ('#Form.ApplicantNo#',
							   '#id#',
							   #RosterActionNo#,
							   '#Edition.DefaultStatus#')
						</cfquery> 
						
						<cfcatch></cfcatch>
						</cftry>
					
					</cfif>
					
				</cfif>	
			
			</cfloop>
						
		<!--- now update the status of this application --->		
				
		<cfif ParameterExists(Form.Status)> 					
					
			<cfquery name="get" 
			 datasource="AppsSelection" 
			 username="#SESSION.login#" 
			 password="#SESSION.dbpw#">
			 SELECT    *
			 FROM      Ref_StatusCode
			 WHERE     Id     = 'Fun' 
			 AND       Owner  = '#url.Owner#'
			 AND       Status = '#Form.Status#'
			</cfquery>

		    <cfset dateValue = "">
		    <CF_DateConvert Value="#Form.StatusDate#">
		    <cfset DTE = dateValue>
			
			<cfif get.EnableStatusDate eq "1">
			  <cfif Form.StatusDate eq "">
				  <script>
					  alert("Set an status effective date")
				  </script>
				  <cfabort>
			  </cfif> 
			</cfif>  
			 			
		
			<cfquery name="UpdateFunctionStatus" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			
				UPDATE    ApplicantFunction 
				SET       Status                = '#Form.Status#',
				          FunctionJustification = '#Form.Remarks#',
						  RosterGroupMemo       = '#Form.ActionRemarks#', 					  
						  <cfif get.EnableStatusDate eq "1">
						  StatusDate            = #dte#  
						  <cfelse>
						  StatusDate            = '#dateformat(now(),client.dateSQL)#'  
						  </cfif>
				WHERE     ApplicantNo           = '#Form.ApplicantNo#'
				AND       FunctionId            = '#Form.FunctionId#'    
			 
			</cfquery>
			
			<!--- log the action and the decision elements --->					
							
			<cfquery name="UpdateFunctionStatusAction" 
			datasource="AppsSelection" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">			
				INSERT INTO  ApplicantFunctionAction (
							   RosterActionId,
							   ApplicantNo,
							   FunctionId, 
							   RosterActionNo, 
							   FunctionJustification, 
							   Status,
							   StatusDate)
				VALUES  (  '#rowguid#',
						   '#Form.ApplicantNo#',
						   '#Form.FunctionId#',
						   #ActionNo#,
						   '#Form.ActionRemarks#', 
						   '#Form.Status#',
						   <cfif get.EnableStatusDate eq "1">
						   #dte#
						   <cfelse>
						   '#dateformat(now(),client.dateSQL)#'
						   </cfif>					   
						   ) 
			</cfquery> 
										
			<cfloop index="itm" list="#Form.DecisionCode#" delimiters=",">
			
				<cfset remarks = Evaluate("Form.Remarks_#itm#")>
			
				<cfquery name="UpdateFunctionStatusDecision" 
				datasource="AppsSelection" 
				username="#SESSION.login#" 
				password="#SESSION.dbpw#">
					INSERT INTO  ApplicantFunctionActionDecision
							   (ApplicantNo, FunctionId, RosterActionNo, DecisionCode, Remarks)
					VALUES    ('#Form.ApplicantNo#',
							   '#Form.FunctionId#',
							   #ActionNo#,
							   '#itm#',
							   <cfif  remarks eq "">
							  	  NULL
							   <cfelse>
							  	 '#remarks#'
							   </cfif>) 
				</cfquery> 
				
			</cfloop>
		
			<!--- process any specific actions : NEW 26/04/2006 --->
			
			<cfquery name="Status" 
				datasource="AppsSelection" 
				username="#SESSION.login#" 
				password="#SESSION.dbpw#">
				SELECT    *
				FROM      Ref_StatusCode
				WHERE     Owner  = '#URL.Owner#' 
				AND       Id     = 'FUN' 
				AND       Status = '#Form.Status#'
			</cfquery>				
			
			<cfif Status.TriggerMethod eq "Roster">
			
				<!--- checks if this person now qualitfies for roster status in general and apply this if needed --->
				
				<cfinvoke component = "Service.RosterStatus"  
				   method           = "RosterSet" 
				   personno         = "#Submission.PersonNo#" 
				   owner            = "#URL.Owner#"
				   returnvariable   = "rosterstatus">	
				   
				   <cfif rosterstatus eq "1">
				       <cfset setstatus = "3">
				   </cfif>
									
			</cfif>
							
		</cfif>				
	
	</cftransaction>	
	
			
	<!--- trigger workflow 22/9/2006 --->
		
	<!--- check if workflow must be triggered --->
		
	<cfif ParameterExists(Form.Status)> 
								
			<!--- trigger an individual eMails based on selected status only --->
			<cfinclude template="ApplicationFunctionDecisionMail.cfm">			
		
			<cfquery name="Check" 
				datasource="AppsSelection" 
				username="#SESSION.login#" 
				password="#SESSION.dbpw#">
				SELECT   *
				FROM     Ref_StatusCode
				WHERE    Status = '#Form.Status#' 
				AND      Owner = '#URL.Owner#' 
				AND      Id = 'FUN'
			</cfquery>
									
			<cfif Check.entityClass neq "">	
				
				<cfquery name="Occ" 
					datasource="AppsSelection" 
					username="#SESSION.login#" 
					password="#SESSION.dbpw#">
					SELECT    F.FunctionDescription, F.OccupationalGroup
					FROM      FunctionOrganization FO INNER JOIN
		            	      FunctionTitle F ON FO.FunctionNo = F.FunctionNo
					WHERE     FO.FunctionId = '#URL.IDFunction#'
				</cfquery>
				
				<cfquery name="Person" 
					datasource="AppsSelection" 
					username="#SESSION.login#" 
					password="#SESSION.dbpw#">
					SELECT     *
					FROM       Applicant
					WHERE      PersonNo IN (SELECT PersonNo 
					                        FROM   ApplicantSubmission 
											WHERE  ApplicantNo = '#Form.ApplicantNo#')
				</cfquery>
				
				<cfset link = "Roster/RosterSpecial/RosterProcess/ApplicationFunctionEdit.cfm?ApplicationFunctionEdit.cfm?Mode=0&ID=#Form.ApplicantNo#&ID1=#URL.IDFunction#&IDFunction=#URL.IDFunction#">
									
				<cf_ActionListing 
						EntityCode       = "EntRosterClearance"
						EntityClass      = "#Check.entityClass#"
						EntityGroup      = "#Occ.OccupationalGroup#"
						EntityStatus     = ""
						OrgUnit          = ""
						PersonNo         = "#Person.PersonNo#" 
						PersonEMail      = "#Person.EMailAddress#"
						ObjectReference  = "#Person.FirstName# #Person.LastName#"
						ObjectReference2 = "#Occ.FunctionDescription#"
						ObjectKey4       = "#rowguid#"
						ObjectURL        = "#link#"
						Show             = "No"					
						Framecolor       = "ECF5FF"
						CompleteFirst    = "No">
				
			</cfif>
			
			
	</cfif>
			
</cfif>	

<cfoutput>
	
	<cfif url.process eq "close">
	
		<script>
			
		    try {
			opener.document.getElementById('refresh').click()
			} catch(e) {}
			window.close();
						
		</script>
		
	<cfelseif url.process eq "memo">	
	
		<script LANGUAGE = "JavaScript">
	
			alert("Remarks were saved.")
			
		</script>	
		
	<cfelse>
								
		<script>
		
			_cf_loadingtexthtml='';	
			<!--- refresh the container --->
			opener.document.getElementById('refresh').click()
			<!--- adjust the [current] process box --->		
		    ColdFusion.navigate('ApplicationFunctionEditCurrent.cfm?id=#FORM.ApplicantNo#&id1=#URL.IDFunction#&owner=#url.owner#&status=#setstatus#','currentbox')			
				<!--- adjust the [current] process box --->		
		    ColdFusion.navigate('ApplicationFunctionEditStatusAction.cfm?owner=#url.owner#&currentstatus=#setstatus#&applicantno=#FORM.ApplicantNo#&functionid=#URL.IDFunction#','setstatusbox')	
			// document.getElementById('move').className = "hide"		
	
		</script>
		
	</cfif>	
	
</cfoutput>

  

