/*
 * Copyright © 2025 Promisan B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
AmCharts.mapTranslations.so = {"Americas":"Afrikada Bari","Eastern Asia":"Aasiyada Bari","Eastern Europe":"Yurubta Bari","United Arab Emirates":"Imaaraadka Carabta ee Midoobay","Afghanistan":"Afgaanistaan","Armenia":"Armeeniya","Angola":"Angoola","Austria":"Osteeriya","Australia":"Awstraaliya","Bosnia and Herzegovina":"Boosniya Heersigoviina","Barbados":"Baarbadoos","Bangladesh":"Bangaala-Deesh","Belgium":"Beljiyam","Bahrain":"Baxrayn","Benin":"Beniin","Brazil":"Braasiil","Canada":"Kanada","Switzerland":"Swiiserlaand","Chile":"Jili","Cameroon":"Kameruun","China":"Shiinaha","Cuba":"Kuuba","Czech Republic":"Jekoslafaakiya","Germany":"Jarmal","Djibouti":"Jabuuti","Denmark":"Danmaark","Ecuador":"Ikwadoor","Egypt":"Masar","Spain":"Isbeyn","Ethiopia":"Itoobiya","Finland":"Fiinlaand","France":"Faransiis","United Kingdom":"United Kingdom","Grenada":"Giriinaada","Guinea":"Gini","Greece":"Giriigga","Croatia":"Korweeshiya","Hungary":"Hangeri","Indonesia":"Indoneesiya","Ireland":"Ayrlaanda","Israel":"Israaʼiil","India":"Hindiya","Iraq":"Ciraaq","Iran":"Iiraan","Iceland":"Iislaand","Italy":"Talyaani","Jamaica":"Jameyka","Jordan":"Urdun","Japan":"Jabbaan","Kenya":"Kiiniya","Cambodia":"Kamboodiya","North Korea":"Kuuriyada Waqooyi","South Korea":"Kuuriyada Koonfureed","Kuwait":"Kuwayt","Kazakhstan":"Kasaakhistaan","Lebanon":"Lubnaan","Sri Lanka":"Siirilaanka","Liberia":"Laybeeriya","Lesotho":"Losooto","Luxembourg":"Luksemboorg","Latvia":"Laatfiya","Libya":"Liibiya","Morocco":"Marooko","Monaco":"Moonako","Macedonia":"Makadooniya","Mali":"Maali","Mauritania":"Muritaaniya","Malta":"Maalda","Maldives":"Maaldiqeen","Malawi":"Malaawi","Mexico":"Meksiko","Mozambique":"Musambiig","Namibia":"Namiibiya","Nigeria":"Nayjeeriya","Nicaragua":"Nikaraaguwa","Norway":"Noorweey","New Zealand":"Neyuusilaand","Oman":"Cumaan","Philippines":"Filibiin","Pakistan":"Bakistaan","Poland":"Booland","Portugal":"Bortuqaal","Qatar":"Qadar","Romania":"Rumaaniya","Russia":"Ruush","Saudi Arabia":"Sacuudi Carabiya","Sudan":"Sudaan","Sweden":"Iswidhan","Sierra Leone":"Siraaliyoon","Somalia":"Soomaaliya","Syria":"Suuriya","Chad":"Jaad","Togo":"Toogo","Thailand":"Taylaand","Tunisia":"Tuniisiya","Tonga":"Tonga","Turkey":"Turki","Tanzania":"Tansaaniya","Uganda":"Ugaanda","United States":"Qaramada Midoobey ee Maraykanka","Vatican City":"Faatikaan","Venezuela":"Fenisuweela","Vietnam":"Fiyetnaam","Yemen":"Yaman","South Africa":"Koonfur Afrika","Zambia":"Saambiya","Zimbabwe":"Simbaabwe","Unknown or Invalid Region":"Far aan la aqoon amase aan saxnayn"};