<!--
    Copyright © 2025 Promisan B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<cfoutput>

<cfsavecontent variable="mailbody">

<cfswitch expression="#URL.Source#">
			
	<cfcase value="ReportConfig">					
		
		This eMail has the following files attached :<br><br>
		
				<cfquery name="report" 
				datasource="appsSystem">
					SELECT   *
				    FROM     Ref_ReportControl 
					WHERE    ControlId = '#URL.SourceId#' 
				</cfquery>
				
				<cfset path = "#Report.ReportPath#">
														
					<cfdirectory action="LIST"
		             directory="#SESSION.rootPath#\#path#"
		             name="GetFiles"
		             type="file">
												
					<cfloop query="getFiles"> 
						   - #Name#<br>
					</cfloop> 
					<br>
					To deploy this report, do the following<br><br>
					
					a. Please copy these files to directory : 				
					<b>Application ROOT/#Report.ReportPath#</b>
					<br>
					b. Run the insert statements [dbscript.txt] using the SQL query Analyser from database System.  
					<br><br>
					You may then open the #SESSION.welcome# Report Manager and test and grant access and further deploy this report.
	
	</cfcase>	
				
	<cfcase value="Release">				 
					
		<table width="100%">
		<tr><td>
			This mail was generated by the #SESSION.welcome# Release Manager.
			</font>
		</td></tr>
		<tr><td></td></tr>
		<tr><td>Release package files attached to this eMail</td></tr>
		<tr><td></td></tr>								
		 <cfquery name="Release" 
			datasource="appsSystem" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
				SELECT S.DistributionEMail,V.*
			    FROM   ParameterSite S, ParameterSiteVersion V
				WHERE  S.ApplicationServer = V.ApplicationServer
				AND    VersionId ='#URL.SourceId#'
		</cfquery>	
		
		<cfdirectory action="LIST"
             directory="#SESSION.rootPath#\_Distribution\#Release.ApplicationServer#\v#DateFormat(Release.VersionDate,'YYYYMMDD')#"
             name="GetFiles"
             filter="*.pdf|*.zip">
												
				<cfloop query="getFiles"> 
				<tr><td>
					   - #Name#
				</td></tr>	   
				</cfloop> 
				
		<tr><td></td></tr>		
		<tr><td>Please apply this package at your earliest convenience. <br> Reply to this eMail once you have deployed this release.</td></tr>				
						
		</table>
					 			
	</cfcase>	
	
	<cfdefaultcase></cfdefaultcase>	
			
</cfswitch>	

</cfsavecontent>

</cfoutput>