<cfparam name="url.batchid"           default="">
<cfparam name="url.warehouse"         default="">
<cfparam name="url.currency"          default="">
<cfparam name="url.terminal"          default="">

<cf_tl id="Print Invoice" var="1">


<!---	
<cf_screentop height="100%" scroll="No" layout="webapp" label="#lt_text#" user="no" banner="gray">
--->

<cfoutput>

	<cfquery name="getBatch"
	 datasource="AppsMaterials" 
	 username="#SESSION.login#" 
	 password="#SESSION.dbpw#">	 
	 SELECT *
	 FROM    WarehouseBatch
	 WHERE   BatchId = '#url.batchId#'
	</cfquery>
	
	<cfquery name="getInvoice"
	 datasource="AppsLedger" 
	 username="#SESSION.login#" 
	 password="#SESSION.dbpw#">	 
		 SELECT A.*, H.Currency, H.OrgUnitTax
		 FROM   TransactionHeader H INNER JOIN TransactionHeaderAction A ON H.Journal = A.Journal AND H.JournalSerialNo = A.JournalSerialNo
		 WHERE  H.TransactionSourceId = '#url.batchId#'
		 AND    H.TransactionCategory = 'Receivables'
		 AND    A.ActionCode          = 'Invoice'
	</cfquery>	
		
	<cfquery name="getWarehouseJournal"
	 datasource="AppsMaterials" 
	 username="#SESSION.login#" 
	 password="#SESSION.dbpw#">
	 	SELECT  *
		FROM    WarehouseJournal
		WHERE   Warehouse = '#getBatch.Warehouse#'
		AND		Area      = 'SETTLE'
		AND		Currency  = '#GetInvoice.currency#'
	</cfquery> 
	
<table width="100%" height="100%">

<cfif getInvoice.ActionMode eq "2" AND getInvoice.ActionReference3 neq "">
	<!--- Invoice was generated by a GFACE --->
	
	<cfif url.terminal eq "">
		<!--- get the terminal from the Invoice number	
		<cfset vTerminal = mid(getInvoice.ActionReference3,1,find(getInvoice.ActionReference2,getInvoice.ActionReference3)-1)>
		<cfset vTerminal = mid(vTerminal,find(getInvoice.ActionReference4) + len(getInvoice.ActionReference4), len(vTerminal) - (find(getInvoice.ActionReference4) + len(getInvoice.ActionReference4)) + 1)>
		--->

		<cfset vTerminal = "">
		

		<cfquery name="getTerminalName"
		 datasource="AppsMaterials" 
		 username="#SESSION.login#" 
		 password="#SESSION.dbpw#">

		 	SELECT *
			FROM   WarehouseTerminal
			WHERE  Warehouse     = '#getBatch.warehouse#'
			AND    Terminal	 	 = '#vTerminal#'
			AND    TaxOrgUnitEDI = '#getInvoice.OrgUnitTax#'
		</cfquery>		
		
		<cfset vTerminal = getTerminalName.TerminalName>
		
	<cfelse>
		<cfset vTerminal = url.terminal>
	</cfif>

	<tr><td></td></tr>
	
	<tr><td height="100%" style="padding:15px;">	
		<cfif getWarehouseJournal.recordCount eq 1 and trim(getWarehouseJournal.TransactionTemplateMode2) neq "">
			<iframe src="#SESSION.root#/#getWarehouseJournal.TransactionTemplateMode2#?batchid=#url.batchid#&terminal=#vTerminal#&source=print" 
			  name="print" id="print" width="100%" height="100%" scrolling="yes" frameborder="0" style="border:1px dashed silver"></iframe>
		<cfelse>
			<table width="100%">
				<tr>
					<td class="labellarge" align="center" style="color:red;"><cf_tl id="The invoice printout is not properly configured !"></td>
				</tr>
			</table>
		</cfif>
			
	</td></tr>
	

<cfelse>

	<!--- MODE = 1 manual mode so we obtain additional information on the invoiceNo --->
	<tr><td></td></tr>
	
	<tr><td height="100%" style="padding:15px;">
		  	
		<cfif getWarehouseJournal.recordCount eq 1 and trim(getWarehouseJournal.TransactionTemplateMode1) neq "">
			<iframe src="#SESSION.root#/#getWarehouseJournal.TransactionTemplateMode1#?batchid=#url.batchid#&terminal=#url.terminal#&source=print" 
			  name="print" id="print" width="100%" height="100%" scrolling="yes" frameborder="0" style="border:1px dashed silver"></iframe>
		<cfelse>
			<table width="100%">
				<tr>
					<td class="labellarge" align="center" style="color:red;">
						<cfif getInvoice.Recordcount eq 0>
							<cf_tl id="Collect Sale process has not finished. This invoice cannot be printed">
						<cfelse>
							<cf_tl id="The invoice printout is not properly configured !">
						</cfif>
				</td>
				</tr>
			</table>
		</cfif>
			
	</td></tr>
	

</cfif>	

	<tr><td height="60" bgcolor="f4f4f4" align="center" style="padding-left:15px; padding-right:15px">
		
		<table width="100%" class="formspacing">
		
		<tr>
		
			<td class="hide" id="process"></td>
										  					
			<td align="center">
			
				<cf_tl id="Close" var="1">
								
				 <input type  = "button" 
				      class   = "button10g"  
					  onclick = "ProsisUI.closeWindow('wreprint',true)"
				      style   = "height:28;width:150;font-size:13px" 
					  class   = "regular" 
					  name    = "save" id="save"
					  value   = "#lt_text#">
		    </td>
						
		</tr>
		
		</table>
	
	</td></tr>


</table>

</cfoutput>