<!--
    Copyright © 2025 Promisan

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->


<!--- 1. mailbody scan --->

<cfsavecontent variable="mailtext">

	<cfoutput>
	
		<table width="99%">
			<tr><td>This eMail has been generated by the #SESSION.welcome# Release Manager.
			</td></tr>
									
			<tr><td></td></tr>
			<tr><td>Release package files attached to this eMail</td></tr>
			<tr><td></td></tr>								
			 <cfquery name="Release" 
				datasource="appsControl" 
				username="#SESSION.login#" 
				password="#SESSION.dbpw#">
				SELECT S.DistributionEMail,V.*
			    FROM ParameterSite S, ParameterSiteVersion V
				WHERE S.ApplicationServer = V.ApplicationServer
				AND VersionId ='#Object.ObjectKeyValue4#'
			</cfquery>	
			
			<cfdirectory action="LIST"
	             directory="#SESSION.rootPath#\_Distribution\#Release.ApplicationServer#\v#DateFormat(Release.VersionDate,'YYYYMMDD')#"
	             name="GetFiles"
	             filter="*.pdf|*.zip">
													
					<cfloop query="getFiles"> 
					<tr><td>
						   - #Name#
					</td></tr>	   
					</cfloop> 
					
			<tr><td></td></tr>		
			<tr><td>Please apply this package at your earliest convenience. <br> Reply to this eMail once you have deployed this release.</td></tr>				
									
		</table>
			
	</cfoutput>		

</cfsavecontent>

<!--- 2. mailsubject --->

<cfset mailSubject = "Release Update v#DateFormat(Release.VersionDate,'YYYYMMDD')#">

	<!--- default from interface --->


<!--- 3. attachments stored in mailatt array --->

<cfquery name="Release" 
			datasource="appsControl" 
			username="#SESSION.login#" 
			password="#SESSION.dbpw#">
			SELECT S.DistributionEMail,V.*
		    FROM   ParameterSite S, 
			       ParameterSiteVersion V
			WHERE  S.ApplicationServer = V.ApplicationServer  
			AND VersionId ='#Object.ObjectKeyValue4#'
</cfquery>		

<cfset mailatt = ArrayNew(2)>

<cfdirectory action="LIST" 
	directory="#SESSION.rootPath#_Distribution\#Release.ApplicationServer#\v#DateFormat(Release.VersionDate,'YYYYMMDD')#" 
	name="GetFiles" filter="*.pdf|*.zip">
	
	<cfset path = "#SESSION.rootPath#_Distribution\#Release.ApplicationServer#\v#DateFormat(Release.VersionDate,'YYYYMMDD')#">
	<cfset purl  = "#SESSION.root#/_Distribution/#Release.ApplicationServer#/v#DateFormat(Release.VersionDate,'YYYYMMDD')#">

	<cfif getFiles.recordcount eq "0">

		<cfset mailatt[1][1] = "">
		<cfset mailatt[1][2] = "">
		<cfset mailatt[1][3] = "&nbsp;&nbsp;&nbsp;<b>Attention</b> : Attachment files could not be located">
	
	</cfif>
		<cfloop query="getFiles"> 
			<cfset mailatt[currentrow][1] = "#path#\#name#">
			<cfset mailatt[currentrow][2] = "#purl#/#name#">
			<cfset mailatt[currentrow][3] = "#name#">
		</cfloop>

	
