<cfinvoke component 	  = "Service.Validation.Controller"  
   method           	  = "Control" 
   systemFunctionId 	  = "#url.systemfunctionid#"		
   mission          	  = "#url.mission#"	  
   object           	  = "Position"
   objectKeyValue1  	  = "#url.PositionNo#"
   target           	  = "validationbox"
   notificationLayout 	  = "mainLayout"
   notificationLayoutArea = "right">