<!--
    Copyright © 2025 Promisan B.V.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<cfparam name="url.header" default="Yes">

<cfajaximport tags="cfwindow">

<cf_filelibraryscript>

<cfparam name="CLIENT.Sort" default="OrgUnit">
<cfparam name="URL.Sort"    default="line">
<cfparam name="URL.View"    default="Hide">
<cfparam name="URL.Lay"     default="Reference">

<cfinvoke component="Service.Access"  
  method="procjob" 
  jobno="#URL.ID1#"
  returnvariable="access">
    
<cfquery name="Job" 
	 datasource="AppsPurchase" 
	 username="#SESSION.login#" 
	 password="#SESSION.dbpw#">
	   SELECT  J.*, R.Description as JobCategoryDescription
	   FROM    Job J LEFT OUTER JOIN Ref_JobCategory R ON  J.JobCategory = R.Code
	   WHERE   J.JobNo ='#URL.Id1#'
</cfquery>

<cfquery name="Check" 
	 datasource="AppsPurchase" 
	 username="#SESSION.login#" 
	 password="#SESSION.dbpw#">
		SELECT    RequisitionNo, 
		          OrgUnitVendor, 
				  Max(Created) as Created
		FROM      RequisitionLineQuote
		WHERE     JobNo ='#URL.Id1#'
		GROUP BY RequisitionNo, OrgUnitVendor
		HAVING    (COUNT(*) > 1)		
</cfquery>		

<cfif Check.recordcount gte "1">

	<cfloop query="Check">
		
		<cfquery name="Clean" 
		 datasource="AppsPurchase" 
		 username="#SESSION.login#" 
		 password="#SESSION.dbpw#">
			DELETE FROM RequisitionLineQuote
			WHERE JobNo ='#URL.Id1#'
			AND   RequisitionNo = '#RequisitionNo#'
			AND   OrgUnitVendor = '#OrgUnitVendor#'
			AND   Created = '#created#' 
		</cfquery>
	
	</cfloop>

</cfif>

<cfoutput>
	
	<!--- Hanno : these scripts can be called from the workflow under custom dialogs which are generated by the config in its setup 
	 DO nOT remove them
	--->
	
	<script>	
	
	function rostersearch(action,actionid) {
    	w = #CLIENT.width# - 90;
	    h = #CLIENT.height# - 160;	
		ptoken.open("#SESSION.root#/Roster/RosterGeneric/RosterSearch/Search1ShortList.cfm?mode=ssa&wActionId="+actionid+"&jobno=#URL.ID1#", "search#url.id1#", "left=35, top=35, width=" + w + ", height= " + h + ", toolbar=no, status=yes, scrollbars=yes, resizable=yes")
	
	}
	
	function purchase(action,actionid) {
		    
		try { parent.ProsisUI.closeWindow('mydialog',true) } catch(e) {}
		
		parent.ProsisUI.createWindow('mydialog', 'Obligation', '',{x:100,y:100,height:parent.document.body.clientHeight-90,width:parent.document.body.clientWidth-90,modal:true,resizable:false,center:true})    						
		parent.ColdFusion.navigate('#SESSION.root#/Procurement/Application/PurchaseOrder/Create/PurchaseCreateView.cfm?actionid='+actionid+'&jobno=#url.id1#&mission=#Job.mission#','mydialog') 					
			
	}
	</script>

</cfoutput>


<cfquery name="FlowDefined" 
	 datasource="AppsOrganization" 
	 username="#SESSION.login#" 
	 password="#SESSION.dbpw#">
		SELECT  *
		FROM    Ref_EntityClassPublish
		WHERE   EntityCode = 'ProcJob' 
		AND     EntityClass = '#Job.OrderClass#'
</cfquery>		
	
<cfquery name="Parameter" 
	datasource="AppsPurchase" 
	username="#SESSION.login#" 
	password="#SESSION.dbpw#">
    SELECT *
    FROM Ref_ParameterMission
	WHERE Mission = '#Job.Mission#' 
</cfquery>
			
<cfif Job.recordcount eq "0">
	 	
  <cf_message message = "Your job [#URL.ID1#] was removed from the system." return="no">
  <cf_screenbottom> 
  <cfabort>
			
</cfif>

<cf_workflowenabled 
	 mission="#job.mission#" 
	 entitycode="ProcJob">

<cfif WorkflowEnabled eq "1" and Job.Jobcategory neq "">

	<cfquery name="Update" 
	   datasource="AppsPurchase" 
	   username="#SESSION.login#" 
	   password="#SESSION.dbpw#">
	   UPDATE Job 
	   SET    ActionStatus = '1'
	   WHERE  JobNo = '#Job.Jobno#'
	   AND    ActionStatus <> '9'
	</cfquery>	
		
</cfif>		

<!--- some code to reset the status in case of incorrectness, should not fire too much --->

<cfquery name="Reset" 
	datasource="AppsPurchase" 
	username="#SESSION.login#" 
	password="#SESSION.dbpw#">	
	UPDATE  RequisitionLine
	SET     ActionStatus = '2k' 
	FROM    RequisitionLine P
	WHERE   JobNo        = '#URL.ID1#'
	AND     ActionStatus = '3'
	AND     (
		        RequisitionNo     IN (SELECT RequisitionNo 
		                              FROM   PurchaseLine 
								      WHERE  ActionStatus  = '9' 
								      AND    RequisitionNo = P.RequisitionNo) 
			    OR 
				
				RequisitionNo NOT IN (SELECT RequisitionNo
				                      FROM   PurchaseLine 
									  WHERE  RequisitionNo = P.RequisitionNo)	
			)
</cfquery> 

<!--- adjust status to 2q --->

<cfquery name="Reset" 
	datasource="AppsPurchase" 
	username="#SESSION.login#" 
	password="#SESSION.dbpw#">
	UPDATE  RequisitionLine
	SET     ActionStatus = '2q'
	FROM    RequisitionLine P
	WHERE   JobNo        = '#URL.ID1#'
	AND     ActionStatus = '2k'
	AND     RequisitionNo IN (SELECT RequisitionNo 
	                          FROM   RequisitionLineQuote 
							  WHERE  RequisitionNo = P.RequisitionNo) 		  
</cfquery> 

<cfquery name="JobOpen" 
	datasource="AppsPurchase" 
	username="#SESSION.login#" 
	password="#SESSION.dbpw#">
	SELECT    JobLine.RequisitionNo, PurL.RequisitionNo AS Purchase
	FROM      RequisitionLine JobLine LEFT OUTER JOIN
	          PurchaseLine PurL ON JobLine.RequisitionNo = PurL.RequisitionNo
	WHERE     JobLine.JobNo = '#URL.ID1#'
	AND       JobLine.ActionStatus NOT IN ('0z','9')
	GROUP BY  JobLine.RequisitionNo, PurL.RequisitionNo
	HAVING    PurL.RequisitionNo IS NULL
</cfquery> 

<!--- check if the job has lines that are PENDING purchase orders --->

<cfquery name="Check" 
	datasource="AppsPurchase" 
	username="#SESSION.login#" 
	password="#SESSION.dbpw#">
	SELECT    *
	FROM      RequisitionLine L
    WHERE     JobNo = '#URL.ID1#' 
	AND       RequisitionNo NOT IN (SELECT RequisitionNo FROM PurchaseLine WHERE RequisitionNo = L.RequisitionNo)
	<!--- was before ActionStatus < '3' --->	  																
</cfquery>

<!--- check of the job has any lines at all --->

<cfquery name="CheckLinesatALL" 
	datasource="AppsPurchase" 
	username="#SESSION.login#" 
	password="#SESSION.dbpw#">
	SELECT    *
	FROM      RequisitionLine 
    WHERE     ActionStatus NOT IN ('0z','9') 
	AND       JobNo = '#URL.ID1#' 
</cfquery>

<cfquery name="CheckBuyer" 
	datasource="AppsPurchase" 
	username="#SESSION.login#" 
	password="#SESSION.dbpw#">
	SELECT    *
	FROM      JobActor 
    WHERE     JobNo       = '#URL.ID1#' 
	AND       ActorUserId = '#SESSION.acc#'
</cfquery>

<cfparam name="URL.mode" default="view">	

<cfif url.mode eq "edit">
	
	<cfif (Access eq "ALL" and (check.recordcount gte "1" or checkLinesAtAll.recordcount eq "0")) or 
	     getAdministrator(job.mission) eq "1">	
		 
	  <cfset url.mode = "Edit">
	  <cfset st = "Edit">	 
	  
	<cfelse>
	
	  <cfset url.mode = "View"> 
	  <cfset st = "Completed">	  
	  
	</cfif>
	
<cfelse>

	<cfif Access eq "ALL" and (check.recordcount gte "1" or checkLinesAtAll.recordcount eq "0")>	
	  <cfset url.mode = "View">
	  <cfset st = "Edit">	 
	<cfelse>
	  <cfset url.mode = "View"> 
	  <cfset st = "Completed">	  
	</cfif>
	
</cfif>				

<cfparam name="URL.Period" default="#Job.Period#">
<cfparam name="URL.Role"   default="">
<cfparam name="URL.Id"     default="Job">

<cfoutput>

<script>

	function reloadJob(mode,sort) {
	  Prosis.busy('yes');
	  ptoken.location("JobViewGeneral.cfm?header=#url.header#&mode="+mode+"&period=#url.period#&id=job&id1=#url.id1#")
	}

</script>
</cfoutput>

<cf_tl id="Inquire and update a procurement job" var="1">

<cf_screenTop height="100%" html="#url.header#" label="#Job.JobNo# (#left(Job.Description,60)#)" layout="webapp" line="no" option="#lt_text#" scroll="yes" banner="gradient" jQuery="yes">

<cf_tl id="Procurement Job" var="1">

<cf_divscroll style="height:100%">
     
	<table width="98%" border="0">
	
	  <tr class="linedotted"><td colspan="4" style="padding-left:20px">
		  
		  <table width="100%">
		  
		  
		  <tr>
		  
		    <td class="labellarge" width="90%" style="height:45px;padding-left:4px">
			
			<cfif url.header eq "no">
				<cfoutput><font size="5"> #Job.JobNo# <cfif job.description neq ""><font size="4">[#Job.Description#]</font></cfif></cfoutput>
			</cfif>
			
			</td>
			
			<td align="right" style="padding-right:4px" class="labelmedium"> 
			
			<cf_space spaces="70">
			
				<cfif url.mode neq "edit">
								
					<cfif (Access eq "ALL" and (check.recordcount gte "1" or checkLinesAtAll.recordcount eq "0"))
					    or getAdministrator(job.mission) eq "1">
					
						<cfoutput>
												
						   <a href="javascript: reloadJob('edit','#url.sort#')"><font color="6688aa">[#st# <cf_tl id="Job">]</font></a>
						   
						</cfoutput>
						
					<cfelse>
					   
					    <cfoutput>#st#</cfoutput>
						
					</cfif>
									
				<cfelse>
				
				    <cfoutput>
					
					    <a href="javascript: reloadJob('view','#url.sort#')"><cf_tl id="view"></a>
						
					</cfoutput>
				
				</cfif>
			
			</td>
			
			<cfif workflowenabled eq "1">
	
	        <td align="right">
	
				<table cellspacing="0" cellpadding="0" align="center">
					
					<tr><td id="vendorshow" class="hide" align="right">
								
					<cfoutput>
					
						<img src="#SESSION.root#/Images/down6.png"
					     alt="Expand"
					     id="l_collapse"
					     border="0"
					     align="absmiddle"
					     style="cursor: pointer;"
					     onClick="showvendor('')">
											 
					 </td>
					 
					 <td id="vendorhide" align="right">
							
						<img src="#SESSION.root#/Images/up6.png"
					     alt="Collapse"
					     id="l_expand"
					     border="0"
					   	 align="absmiddle"
					     style="cursor: pointer;"
					     onClick="showvendor('')">
											 
					 </td>
					 </tr>
					 </cfoutput>		
					 
				 </table>
	 	 
		</td>		
	 
		</cfif> 
		  				 
		 </tr>
				 
		 </table>
	  
	  </td></tr>
	  
	  <tr class="line">
	  <td colspan="4" style="padding-left:15px">
	  
	  <cfform action="JobUpdateSubmit.cfm?Role=#URL.Role#&Period=#URL.Period#&ID=#URL.ID#&ID1=#URL.ID1#&Sort=#URL.Sort#" method="post">
			  
		  <cfoutput query="Job" maxrows="1">
		  
			  <table width="99%" align="center">
		
				<tr><td colspan="2" style="padding-left:4px;<cfif URL.Mode eq 'view'>background-color:f1f1f1</cfif>">				
												
				<table width="100%" class="<cfif URL.Mode neq 'view'>formspacing</cfif>">
																	
				<tr class="labelmedium">
				   
				   <td width="20%" style="height:25px">
				       <cfif URL.Mode eq "view">
					        #OrderClass# - <cfif JobCategoryDescription eq ""><cf_tl id="not categorised"><cfelse>#JobCategoryDescription#</cfif>
					   <cfelse>
					        #OrderClass# - <cfif JobCategoryDescription eq ""><cf_tl id="not categorised"><cfelse>#JobCategoryDescription#</cfif>			       
					   </cfif>		
					   </td>
				   </td>
				   <td colspan="3" style="height:25px">
				   		   
			   	       <cfif URL.Mode eq "view">
					        #Description#
					   <cfelse>			  
				       	<input class="regularxl" value="#Description#" style="width:94%" type="text" name="Description" id="Description" size="80" maxlength="80">
					   </cfif>
					  
				   </td>
				</tr>
													
				<tr class="labelmedium">
				   <td style="height:25px"><cf_tl id="#Parameter.JobReferenceName#">:</td>
				   <td width="30%" style="height:20px">
				   <table class="formpadding">
				   <tr class="labelmedium">
				   	   <cfif URL.Mode eq "view">
					       <td style="height:20px">#CaseNo# </td>
					   <cfelse>
					       <td>
						   
					       <input class="regularxl" 
							   type="text" 
							   value="#CaseNo#" 
							   name="CaseNo" 
			                   id="CaseNo"
							   size="20" 
							   onchange="ptoken.navigate('JobCaseCheck.cfm?mission=#job.mission#&jobNo=#url.id1#&caseNo='+this.value,'casenocheck')"			
							   maxlength="20">
							   
						   </td>
						   <td style="height:20px;padding-left:4px">						   
						   	<cf_securediv bind="url:JobCaseCheck.cfm?mission=#job.mission#&jobNo=#url.id1#&caseNo=#job.CaseNo#" id="casenocheck">				   
						   </td>
					   </cfif>
					   </tr>
				   </table>   
				   </td>
				   <td width="130" style="height:20px"><cf_tl id="Submission">:</td>
				   <td width="30%">
				   	   <table cellspacing="0" cellpadding="0">
					   <tr><td>
					   
				   	   <cfif URL.Mode eq "view">
					   		
							<cfif deadline neq "">
					        <b>#Dateformat(deadline, CLIENT.DateFormatShow)#
							<cfelse>
							--
							</cfif>
							
					   <cfelse>
					   
						   	<cf_calendarscript>
					   
						   <cf_intelliCalendarDate9
							FieldName="deadline" 					
							Default="#Dateformat(deadline, CLIENT.DateFormatShow)#"
							AllowBlank="True"
							class="regularxl">						
							
						</cfif>	
						</td>
						<td style="height:20px">&nbsp;<cf_tl id="Hour">:&nbsp;</td>
						<td style="height:20px">
						
						<cfif URL.Mode eq "view">
						
						    <cfif deadline neq "">
							<cfif len(deadlinehour) eq "1">0</cfif>#deadlinehour#<cfelse>--</cfif>
						 
						<cfelse>
						 
							<select name="deadlinehour" id="deadlinehour" class="regularxl">
								<cfloop index="hr" from="1" to="24">
									<option value="#hr#" <cfif hr eq deadlinehour>selected</cfif>><cfif len(hr) eq 1>0</cfif>#hr#</option>
								</cfloop>					
							</select> 
						
						</cfif>
						
						</td> 
						</tr>
						</table>	
									   
				   </td>
				</tr>
				
				<tr class="labelmedium">
				   <td style="height:25px"><cf_tl id="Contact/Delivery">:</td>
				   <td style="height:25px">
				   	   <cfif URL.Mode eq "view">
					        <cfif QuotationContact eq "">
							n/a
							<cfelse>
							#QuotationContact#
							</cfif>
					   <cfelse>
					       <input class="regularxl" type="text" value="#QuotationContact#" name="QuotationContact" id="QuotationContact" size="30" maxlength="60">
					   </cfif>
				   </td>
				   <td style="height:20px"><cf_tl id="Period">:</td>
				   <td style="height:20px">
				      
					 <cfif URL.Mode eq "view"> #Job.Period#
					 <cfelse> 
							   
					<cfquery name="PeriodList" 
						datasource="AppsPurchase" 
						username="#SESSION.login#" 
						password="#SESSION.dbpw#">
						SELECT  Period
						FROM    Program.dbo.Ref_Period
						WHERE   Period = '#Job.Period#'
						UNION 
						SELECT  Period
						FROM    RequisitionLine
						WHERE   JobNo = '#Job.Jobno#'	
					</cfquery> 
					
					<select name="Period" class="regularxl">
						<cfloop query="PeriodList">
						   <option value="#Period#" <cfif period eq Job.Period>selected</cfif>>#Period#</option>
						</cfloop>
					</select>
					
					</cfif>
				   
				   </td>
				</tr>  		
										
				<tr class="labelmedium">
				   <td style="height:25px"><cf_tl id="Reference">:</td>
				   <td style="height:25px">
				   
				   	   <cfif URL.Mode eq "view">
					        
							<cfif CaseReference eq "">
								n/a
							<cfelse>
								#CaseReference#
							</cfif>
							
					   <cfelse>
					   
					       <input class="regularxl" type="text" value="#CaseReference#" name="CaseReference" id="CaseReference" size="20" maxlength="20">
						   
					   </cfif>
					   
				   </td>
				   <td><cf_tl id="Status">:</td>
				   <td id="jobstatus">
				   
				    <cfif ActionStatus neq "9">
					
					    <cfif URL.Mode eq "edit">
						
						    <!--- check if job is active --->
						
							<cfif Check.recordcount gte "1" or CheckLinesAtAll.recordcount eq "0">
							    <a href="javascript:ColdFusion.navigate('JobStatus.cfm?jobno=#jobno#&actionstatus=9','jobstatus')" title="Cancel">[<cf_tl id="Press to cancel">]</a></font>
							<cfelse>
							   <font color="6688aa"><cf_tl id="Active"></font>
							</cfif>	
							
						<cfelse>
									
						   [#st#]
						   
						</cfif>
					
					<cfelse>
					
						<cfif URL.Mode eq "edit">
							<b><a href="javascript:ptoken.navigate('JobStatus.cfm?jobno=#jobno#&actionstatus=1','jobstatus')" title="Reactivate"><cf_tl id="Press to activate"></a>
						<cfelse>
							<font color="red"><cf_tl id="Cancelled"></font>
						</cfif>
						
					</cfif>
					
				   </td>
				 
				</tr>
				
				<cfif QuotationRemarks neq "" and URL.Mode eq "view">
											
					<tr class="labelmedium">
					   <td valign="top" style="padding-top:3px"><cf_tl id="Memo">:</td>
					   <td colspan="3">			       
					       <cfif URL.Mode eq "view">
						        <cfif QuotationRemarks eq "">
								n/a
								<cfelse>
						        #QuotationRemarks#
								</cfif>
						   <cfelse>				  
						       <textarea style="width:100%;height:40" totlength="400" onkeyup="return ismaxlength(this)" class="regular" name="QuotationRemarks">#QuotationRemarks#</textarea>	
						   </cfif>
					   </td>
					</tr>
					
				<cfelse>
				
					<tr class="labelmedium">
					   <td valign="top" style="padding-top:3px" height="20"><cf_tl id="Memo/Justification">:</td>
					   <td colspan="3">
					       <cfif URL.Mode eq "view">
						        <cfif QuotationRemarks eq "">
								n/a
								<cfelse>
						        #QuotationRemarks#
								</cfif>
						   <cfelse>
						       <textarea style="padding:3px;font-size:13px;border-radius:3px;width:100%;height:40" totlength="400" onkeyup="return ismaxlength(this)" class="regular" name="QuotationRemarks">#QuotationRemarks#</textarea>	
						   </cfif>
					   </td>
					</tr>
						
				</cfif>
								
				<cfif QuotationContact neq "">		
					
				<tr class="labelmedium">
				   <td><cf_tl id="Contact">:</td>
				   <td colspan="3">
					   <cfif URL.Mode eq "view">
					        <b>#QuotationContact#
					   <cfelse>
				       		<input class="regularxl" type="text" value="#QuotationContact#" name="QuotationContact" id="QuotationContact" size="80" maxlength="80">
					   </cfif>
				   </td>
				   <td></td>
				</tr>
				
				</cfif>
						  			   
				<cfquery name="Requisition" 
					datasource="AppsPurchase" 
					username="#SESSION.login#" 
					password="#SESSION.dbpw#">
					SELECT    sum(RequestAmountBase) as RequestAmount
					FROM      RequisitionLine 
					<!---  WHERE     ActionStatus IN ('2k','3') --->
					WHERE ActionStatus != '9' and ActionStatus != '0z'			
					AND       JobNo    = '#URL.ID1#' 
					<!---
					AND       Period   = '#URL.Period#' 
					--->
				</cfquery>
				
				<cfif Requisition.RequestAmount neq "">
								
					<tr class="labelmedium2">
					   <td style="height:25px;padding-top:4px" valign="top"><cf_tl id="Ceiling for Purchase">:</td>
					   <td style="height:25px;font-size:20px">
					   <cfset tot = Requisition.RequestAmount+Parameter.PurchaseExceed/100*Requisition.RequestAmount>			   
					   <font color="black"><font size="2">#APPLICATION.BaseCurrency#</font> #NumberFormat(tot, ",.__")# 			   
					   <cfif Parameter.TaxExemption eq "0">(<cf_tl id="without tax">)</cfif>	   
					   </td>
					</tr>			
				
				</cfif>		
				
				 <cfif URL.Mode eq "view">
				 
				 	 <cf_fileExist
						DocumentPath="ProcurementJob"
						SubDirectory="#URL.ID1#" 
						Filter="Job">	
						
					 <cfif files gte "1">	
				 
					 <tr class="line labelmedium">
					   <td style="height:20px"><cf_tl id="Attachments">:</td>
					   <td colspan="3" style="padding-bottom:3px">
					 
						 <cf_filelibraryN
									DocumentPath="ProcurementJob"
									SubDirectory="#URL.ID1#" 
									Filter="Job"					
									loadscript="No"
									Insert="no"
									Remove="no"
									reload="true"		
									width="100%"
									align="left"
									border="1">						
								
					   </td>		
					
					</tr>	
					
					</cfif>
				 
				 <cfelse>
				
					<tr class="line labelmedium">
					   <td style="height:20px"><cf_tl id="Attachments">:</td>
					   <td colspan="3" style="padding-bottom:3px">		   		   
										
							<cf_filelibraryN
									DocumentPath="ProcurementJob"
									SubDirectory="#URL.ID1#" 
									Filter="Job"						
									Insert="yes"		
									loadscript="No"	
									Remove="yes"
									width="100%"		
									AttachDialog="yes"
									align="left"
									border="1">						
						
					   </td>		
					
					</tr>	
				
				</cfif>		
										
				<cfif URL.Mode eq "edit">
				
					<cfquery name="Check" 
					datasource="AppsPurchase" 
					username="#SESSION.login#" 
					password="#SESSION.dbpw#">
						SELECT    *
						FROM      RequisitionLine 
			            WHERE     ActionStatus = '3' <!--- procured --->
						AND       JobNo    = '#URL.ID1#' 			
					</cfquery>						
					
					<tr><td colspan="4" align="center">
					
						<cfif check.recordcount eq "0">
						
						<input class    = "Button10g" 
							Value       = "Delete"
							type        = "Submit"		
							id          = "Delete"	
							name        = "Delete"				
							style       = "width:170px">   
										
						</cfif>
						
						<input class    = "Button10g" 
							type        = "Submit"		
							Value       = "Save"
							id          = "Save"		
							name        = "Save"			
							style       = "width:170px">   
						
						
						</td>
					</tr>
													
					<tr><td colspan="4">			
						<cfinclude template="BuyerListing.cfm">							
					</td></tr>	
					
				</cfif>			
													
			  </table>
			  					  		  
			  </td></tr> 	
			  
			  </table> 
		  
	    </cfoutput>
	
	</cfform>
	
	</td></tr>			
	
	<cfquery name="Parameter" 
	  datasource="AppsPurchase" 
	  username="#SESSION.login#" 
	  password="#SESSION.dbpw#">
	      SELECT *
	      FROM   Ref_ParameterMission
		  WHERE  Mission = '#Job.Mission#' 
	</cfquery>
	
	<cfquery name="Class" 
	  datasource="AppsPurchase" 
	  username="#SESSION.login#" 
	  password="#SESSION.dbpw#">
	      SELECT *
	      FROM   Ref_OrderClass
		  WHERE  Code = '#Job.OrderClass#' 
	</cfquery>	
		
	<cfif WorkflowEnabled eq "1" and flowdefined.recordcount gte "1" and Job.JobCategory neq "" and Class.PreparationMode neq "Direct">
	  <cfset trigwf = "1">	  
	<cfelse>
	  <cfset trigwf = "0">	
	</cfif>  
	
	<!--- show vendor and quotes --->
    <cfinclude template="JobViewVendorScript.cfm">		
	
	<tr><td colspan="4" style="padding-left:20px" id="fundingstatus">		
	    <cfinclude template="JobFundingSufficient.cfm">		
	</td></tr>
	
	<cfif Class.PreparationMode eq "SSA">
		
	  <tr id="dialogbox"><td colspan="4" id="dialog" style="padding-left:20px">

	  	  <cfset url.workflow = "1">
		  <!--- show vendor and quotes --->
		  <cfinclude template="JobViewLines.cfm">			
		  
	  </td></tr>
	
	<cfelse>
				
		<tr id="dialogbox" height="1"><td colspan="4" style="padding-left:20px">

		     <cfdiv id="dialog">			 
		    	 <cfinclude template="JobViewVendor.cfm">	
			 </cfdiv>
		</td></tr>				
	
	</cfif>
	
	<input type  = "button" 
	     class   = "hide"
	     name    = "workflowlinkprocess_#job.JobNo#" 
         id      = "workflowlinkprocess_#job.JobNo#"
	     onclick = "ptoken.navigate('JobViewLines.cfm?id1=#url.id1#','dialog');ptoken.navigate('JobFundingSufficient.cfm?id1=#url.id1#&period=#url.period#','fundingstatus')">		   				   
				
		
	<cfif trigwf eq "1">	
			
		<cfoutput>
		
			<cfajaximport tags="cfdiv,cfwindow">
			<cf_ActionListingScript>
						
			<cfset wflnk = "JobViewWorkflow.cfm">
			
			<input type    = "hidden" 
		   	       name    = "workflowlink_#job.JobNo#" 
                   id      = "workflowlink_#job.JobNo#"
				   value   = "#wflnk#">		
						   
			<input id="workflowbutton_#job.JobNo#" type="hidden" onclick="ptoken.navigate('#wflnk#?ajaxid=#job.JobNo#','#job.JobNo#')">	   
		   		   			    			
			<tr><td id="#job.JobNo#" style="padding-left:20px">
			
			    <cfset url.ajaxid = "#job.JobNo#">
				<cfinclude template="JobViewWorkflow.cfm">			
			
			</td></tr>				 
							
		</cfoutput>		
				
	
	</cfif>
						
</TABLE>

</cf_divscroll>

<cf_screenbottom html="#URL.Header#" layout="webapp">	

