<cfinvoke component 	= "Service.Validation.Controller"  
   method           	= "Control" 
   systemFunctionId 	= "#url.systemfunctionid#"		
   mission          	= "#url.mission#"	  
   object           	= "Program"
   objectKeyValue1  	= "#url.ProgramId#"
   target           	= "validationbox"
   notificationLayout 	= "mainLayout"
   notificationLayoutArea = "right">